### ISSUE TITLE
Critical error (swagger-themes library)

### ISSUE THREAD

**Issue by ilyamixaltik** [SoyaNyan/google-map-api#1]
Unfortunately, a critical error was found in the swagger-themes library. Because of it, the library might not work with JS code (only with TS). Kindly update the library to the latest version (currently the latest version is 1.2.22)

**Comment by SoyaNyan** [comment]
Yes, I found the issue when I'm testing the api.
So I added build script to package.json that builds swagger-themes package.
The issue seems occurred cause the package has no js entry.
After build swagger-themes, it will work.

`yarn swagger-themes:build`

** Note: I published ts version of this project as google-map-api-v2. If you're interested check that too.

**Comment by SoyaNyan** [comment]
I updated 'swagger-themes' to latest version (1.2.22)
